---
Mappings:
  RegionEC2InstanceImageMap:
    us-east-1:
      HVM64: ami-079db87dc4c10ac91 
      HVM32: ami-02cd6549baea35b55
    ap-southeast-1:
      HVM64: ami-0390917f7df0de28c
      HVM32: ami-0e5182fad1edfaa68

Parameters:
  EC2InstanceType:
    Description: The Instance Type Chosen for EC2
    Type: String
    
Resources:
  TekLoonTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: !FindInMap
        - RegionEC2InstanceImageMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref HTTPSecurityGroup
  sushantInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: !FindInMap
        - RegionEC2InstanceImageMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref HTTPSecurityGroup

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable port 80 and port 443
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
